Support svc account annotation
depends on #1102 to avoid

Error: Service "foo2" is invalid: metadata.annotations: Invalid value:
"alpha.istio.io/serviceaccounts/kubernetes": a qualified name must
consist of alphanumeric characters